ACCEPT_COOKIES_BTN_SELECTOR = 'form div[data-is-touch-wrapper] button'
ACCEPT_COOKIES_BTN_XPATH = '/html/body/div[2]/div[3]/span/div/div/div/div[3]/div[1]/button[1]'
SEARCH_BOX_SELECTOR = '#searchboxinput'
SIDEBAR_CONTAINER_SELECTOR = 'div[aria-label][tabindex="-1"][role="feed"]'
LISTING_ITEM_CHILD_SELECTOR = 'div > div[jsaction] > a[aria-label][jsaction][jslog]'
DETAIL_PANEL_SELECTOR = 'div[class][style][aria-label][role="main"][jslog]'
BUSINESS_NAME_SELECTOR = 'h1:not([aria-label])'
BUSINESS_RATING_SELECTOR = 'span[role="img"] > span[aria-hidden="true"]'
BUSINESS_NUM_REVIEWS_SELECTOR = 'span[role="img"] > span[aria-hidden="true"]:nth-of-type(2)'
BUSINESS_ADDRESS_SELECTOR = 'button[data-item-id="address"] > div > div:nth-of-type(2)'
BUSINESS_PHONE_SELECTOR = 'button[data-tooltip][data-item-id*="tel:"] > div > div:nth-of-type(2)'
BUSINESS_BOOKING_LINK_SELECTOR = 'a[data-tooltip][data-item-id="action:3"]'
BUSINESS_WEBSITE_SELECTOR = 'a[data-tooltip][data-item-id="authority"]'
BUSINESS_CATEGORY_SELECTOR = 'button[jsaction*="category"]'
BUSINESS_HOURS_ITEM_SELECTOR = 'button[data-value][jsaction*="openhours"]'
BUSINESS_MAIN_IMAGE_SELECTOR = 'button[jsaction*="heroHeaderImage"] img'
BUSINESS_INFO_SELECTOR = 'button[jsaction*="attributes.expand"] > div:nth-of-type(3) > div > div:nth-of-type(1) > div'
BUSINESS_METADATA_SELECTOR = 'button[jsaction*="attributes.expand"] > div:nth-of-type(3) > div > div'
BUSINESS_ATTRIBUTES_SELECTOR = 'button[jsaction*="attributes.expand"] > div:nth-of-type(3) > div > div > div[role="group"]'
BUSINESS_REVIEWS_SELECTOR = 'div[data-review-id][jsaction*="review.in"]'
BUSINESS_REVIEW_VIEW_MORE_SELECTOR = 'button[jsaction*="expandReview"]'
BUSINESS_REVIEW_CONTAINER_CHILD_SELECTOR = 'div > div:nth-of-type(4)'
BUSINESS_REVIEW_RATING_SELECTOR = 'span[role="img"][aria-label]'
BUSINESS_REVIEWER_CONTAINER_CHILD_SELECTOR = 'button[jsaction*="reviewerLink"] > div:nth-of-type(1)'
BUSINESS_REVIEW_PHOTO_SELECTOR = 'button[jsaction*="openPhoto"]'
DETAIL_PANEL_REVIEWS_TAB_SELECTOR = 'div[role="tablist"] button[role="tab"][aria-label^="Reviews"]'
DETAIL_PANEL_REVIEWS_SCROLLABLE_SELECTOR = 'div[jsaction*="scrollable"] div[aria-label="{place_name}"][role="main"][jslog*="mutable"] div[tabindex="-1"][jslog*="mutable"]'

